---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	fetch_user_info(fetch_user_info)
	supervisor_agent(supervisor_agent)
	research_agent(research_agent)
	flight_booking_agent(flight_booking_agent)
	hotel_booking_agent(hotel_booking_agent)
	car_rental_booking_agent(car_rental_booking_agent)
	excursion_booking_agent(excursion_booking_agent)
	train_booking_agent(train_booking_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> fetch_user_info;
	car_rental_booking_agent -.-> __end__;
	excursion_booking_agent -.-> __end__;
	fetch_user_info --> supervisor_agent;
	flight_booking_agent -.-> __end__;
	hotel_booking_agent -.-> __end__;
	research_agent -.-> __end__;
	supervisor_agent -.-> __end__;
	supervisor_agent -.-> car_rental_booking_agent;
	supervisor_agent -.-> excursion_booking_agent;
	supervisor_agent -.-> flight_booking_agent;
	supervisor_agent -.-> hotel_booking_agent;
	supervisor_agent -.-> research_agent;
	supervisor_agent -.-> train_booking_agent;
	train_booking_agent -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2,stroke:#5a3e9e,color:#5a3e9e
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
